const prompt = require("prompt-sync")()
console.clear()
let oP2040 = null
const mP2040 = ['RISCO NA VERTICAL','MODO MANUTENÇÃO','CÓDIGO DE ERRO 0100']
//MANUTENÇÃO DE HARDWARE - P2040
const mnMntP2040 = function mMp2040() {
    while(oP2040!='S') {
        console.clear()
        console.log('')
        console.log('=================================')
        console.log('|      MANUTENÇÃO DA P2040      |')
        console.log('=================================')
        console.log('|        MARCAS NO PAPEL        |')
        console.log('|-------------------------------|')
        console.log('|[1] RISCO NA VERTICAL          |')
        console.log('|[!] MANCHA NA HORIZONTAL       |')
        console.log('|[!] MANCHA ESCURA NA BORDA     |')
        console.log('|[!] MANCHA NO VERSO            |')
        console.log('|[!] BORRÃO                     |')
        console.log('|-------------------------------|')
        console.log('|       OBSTRUÇÃO DE PAPEL      |')
        console.log('|-------------------------------|')
        console.log('|[!] GAVETA                     |')
        console.log('|[!] BANDEJA MP                 |')
        console.log('|[!] BY PASS                    |')
        console.log('|[!] UNIDADE DE CILINDRO        |')
        console.log('|[!] UNIDADE DE FUSÃO           |')
        console.log('|[!] UNIDADE DUPLEX             |')
        console.log('|[!] BANDEJA DE SAÍDA           |')
        console.log('|-------------------------------|')
        console.log('|      RUÍDO AO FUNCIONAR       |')
        console.log('|-------------------------------|')
        console.log('|[!] TAMPA FRONTAL              |')
        console.log('|[!] TAMPA TRASEIRA             |')
        console.log('|[!] LATERAL DIREITA            |')
        console.log('|[!] LATERAL ESQUERDA           |')
        console.log('|[!] LADO INFERIOR              |')
        console.log('|[!] EQUIPAMENTO NÃO LIGA       |')
        console.log('|-------------------------------|')
        console.log('|    CONFIGURAÇÕES & AJUSTES    |')
        console.log('|-------------------------------|')
        console.log('|[!] PREPARAÇÃO                 |')
        console.log('|[!] REDE                       |')
        console.log('|[!] PAPEL                      |')
        console.log('|[2] MODO MANUTENÇÃO (1087+1087)|')
        console.log('|[!] CONFIGURAÇÕES E SERVIÇOS   |')
        console.log('|-------------------------------|')
        console.log('|        CÓDIGO DE ERROS        |')
        console.log('|-------------------------------|')
        console.log('|[3] 0100s                      |')
        console.log('|[!] 0500s                      |')
        console.log('|[!] 0800s                      |')
        console.log('|[!] 0900s                      |')
        console.log('|[!] 1800s                      |')
        console.log('|[!] 2000s                      |')
        console.log('|[!] 4000s                      |')
        console.log('|[!] 6000s                      |')
        console.log('|[!] 7000s                      |')
        console.log('|[!] Fs                         |')
        console.log('=================================')
        console.log('|[V] Voltar                     |')
        console.log('|[S] Sair                       |')
        console.log('=================================')
        console.log(mP2040[oP2040-1])
        console.log('')
        oP2040 = prompt('Digite a opção: ')
        if (oP2040>0 && oP2040<3) {
            console.log(mP2040[oP2040-1])
        } else if (oP2040=='S') {
            console.log('Saindo...')
            process.exit(0)
        } else if (oP2040=='V') {
            return
        } else {
            console.log('ERRO! Opção invalida!')
        }
    }
}

module.exports = mnMntP2040