//MANUTENÇÃO DE HARDWARE - KYOCERA
function manutencaoP2040() {
    console.log('')
    console.log('=================================')
    console.log('|      MANUTENÇÃO DA P2040      |')
    console.log('=================================')
    console.log('|        MARCAS NO PAPEL        |')
    console.log('|-------------------------------|')
    console.log('|[1] RISCO NA VERTICAL          |')
    console.log('|[2] MANCHA NA HORIZONTAL       |')
    console.log('|[3] MANCHA ESCURA NA BORDA     |')
    console.log('|[4] MANCHA NO VERSO            |')
    console.log('|[5] BORRÃO                     |')
    console.log('|-------------------------------|')
    console.log('|       OBSTRUÇÃO DE PAPEL      |')
    console.log('|-------------------------------|')
    console.log('|[6] GAVETA                     |')
    console.log('|[7] BANDEJA MP                 |')
    console.log('|[8] BY PASS                    |')
    console.log('|[9] UNIDADE DE CILINDRO        |')
    console.log('|[10] UNIDADE DE FUSÃO          |')
    console.log('|[11] UNIDADE DUPLEX            |')
    console.log('|[12] BANDEJA DE SAÍDA          |')
    console.log('|-------------------------------|')
    console.log('|      RUÍDO AO FUNCIONAR       |')
    console.log('|-------------------------------|')
    console.log('|[13] TAMPA FRONTAL             |')
    console.log('|[14] TAMPA TRASEIRA            |')
    console.log('|[15] LATERAL DIREITA           |')
    console.log('|[16] LATERAL ESQUERDA          |')
    console.log('|[17] LADO INFERIOR             |')
    console.log('|-------------------------------|')
    console.log('|[18] EQUIPAMENTO NÃO LIGA      |')
    console.log('=================================')
    console.log('|[V] Voltar                     |')
    console.log('|[S] Sair                       |')
    console.log('=================================')
    console.log('')
}